# Generated by Django 5.0.1 on 2024-02-19 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0002_task_cod_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="name_user",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="task",
            name="observations",
            field=models.TextField(blank=True),
        ),
    ]
